<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TracNghiemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trac_nghiems')->delete();
        DB::table('trac_nghiems')->truncate();
        DB::table('trac_nghiems')->insert([
            [
                'cau_hoi'   => 'Laravel sử dụng hệ quản trị cơ sở dữ liệu nào mặc định?',
                'dap_an_1'  => 'MySQL',
                'dap_an_2'  => 'PostgreSQL',
                'dap_an_3'  => 'SQLite',
                'dap_an_4'  => 'MongoDB',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào dùng để tạo một migration trong Laravel?',
                'dap_an_1' => 'php artisan make:model',
                'dap_an_2' => 'php artisan make:controller',
                'dap_an_3' => 'php artisan make:migration',
                'dap_an_4' => 'php artisan migrate',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'File cấu hình cơ sở dữ liệu nằm trong thư mục nào của Laravel?',
                'dap_an_1' => 'app/',
                'dap_an_2' => 'config/',
                'dap_an_3' => 'routes/',
                'dap_an_4' => 'public/',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào được sử dụng để chạy migration trong Laravel?',
                'dap_an_1' => 'php artisan migrate:rollback',
                'dap_an_2' => 'php artisan migrate:refresh',
                'dap_an_3' => 'php artisan migrate:install',
                'dap_an_4' => 'php artisan migrate',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Blade là gì trong Laravel?',
                'dap_an_1' => 'Một ORM',
                'dap_an_2' => 'Một công cụ template',
                'dap_an_3' => 'Một middleware',
                'dap_an_4' => 'Một gói (package)',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào dùng để tạo controller trong Laravel?',
                'dap_an_1' => 'php artisan make:middleware',
                'dap_an_2' => 'php artisan make:model',
                'dap_an_3' => 'php artisan make:controller',
                'dap_an_4' => 'php artisan make:seeder',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Middleware trong Laravel dùng để làm gì?',
                'dap_an_1' => 'Xử lý các yêu cầu HTTP trước khi đến controller',
                'dap_an_2' => 'Tạo route cho ứng dụng',
                'dap_an_3' => 'Quản lý cơ sở dữ liệu',
                'dap_an_4' => 'Quản lý view',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Thư mục nào trong Laravel chứa các model?',
                'dap_an_1' => 'config/',
                'dap_an_2' => 'app/Models/',
                'dap_an_3' => 'resources/views/',
                'dap_an_4' => 'routes/',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Câu lệnh nào dùng để seed dữ liệu trong Laravel?',
                'dap_an_1' => 'php artisan make:seeder',
                'dap_an_2' => 'php artisan db:seed',
                'dap_an_3' => 'php artisan migrate',
                'dap_an_4' => 'php artisan migrate:seed',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Phương thức nào trong model được dùng để định nghĩa quan hệ một-nhiều?',
                'dap_an_1' => 'hasOne()',
                'dap_an_2' => 'hasMany()',
                'dap_an_3' => 'belongsTo()',
                'dap_an_4' => 'belongsToMany()',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Laravel hỗ trợ caching với driver nào?',
                'dap_an_1' => 'Redis',
                'dap_an_2' => 'Memcached',
                'dap_an_3' => 'File',
                'dap_an_4' => 'Tất cả các phương án trên',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào tạo một seeder trong Laravel?',
                'dap_an_1' => 'php artisan db:seed',
                'dap_an_2' => 'php artisan make:seeder',
                'dap_an_3' => 'php artisan make:seed',
                'dap_an_4' => 'php artisan seed',
                'dap_an_dung' => 2,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Thư mục nào chứa các file view trong Laravel?',
                'dap_an_1' => 'resources/views',
                'dap_an_2' => 'public/views',
                'dap_an_3' => 'views/',
                'dap_an_4' => 'app/views',
                'dap_an_dung' => 1,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Phương thức nào dùng để redirect trong Laravel?',
                'dap_an_1' => 'return redirect()',
                'dap_an_2' => 'return route()',
                'dap_an_3' => 'return view()',
                'dap_an_4' => 'return back()',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào tạo authentication trong Laravel?',
                'dap_an_1' => 'php artisan auth:make',
                'dap_an_2' => 'php artisan ui:auth',
                'dap_an_3' => 'php artisan make:auth',
                'dap_an_4' => 'php artisan auth',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Phương thức nào trong Vue.js được gọi khi component đã được mount?',
                'dap_an_1' => 'created()',
                'dap_an_2' => 'mounted()',
                'dap_an_3' => 'beforeMount()',
                'dap_an_4' => 'updated()',
                'dap_an_dung' => 2,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Thuộc tính nào trong Vue.js được sử dụng để theo dõi trạng thái của component?',
                'dap_an_1' => 'props',
                'dap_an_2' => 'state',
                'dap_an_3' => 'data',
                'dap_an_4' => 'methods',
                'dap_an_dung' => 3,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Lệnh nào dùng để tạo dự án Vue.js?',
                'dap_an_1' => 'vue create',
                'dap_an_2' => 'npm install vue',
                'dap_an_3' => 'vue new',
                'dap_an_4' => 'vue init',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Vue.js là một framework front-end hay back-end?',
                'dap_an_1' => 'Front-end',
                'dap_an_2' => 'Back-end',
                'dap_an_3' => 'Full-stack',
                'dap_an_4' => 'Không phải framework',
                'dap_an_dung' => 1,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Directive nào dùng để lặp qua một danh sách trong Vue.js?',
                'dap_an_1' => 'v-if',
                'dap_an_2' => 'v-bind',
                'dap_an_3' => 'v-on',
                'dap_an_4' => 'v-for',
                'dap_an_dung' => 4,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Lệnh nào để cài đặt Vue Router?',
                'dap_an_1' => 'npm install vue-router',
                'dap_an_2' => 'npm add vue-router',
                'dap_an_3' => 'npm install router',
                'dap_an_4' => 'npm add router',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'Vuex dùng để làm gì trong Vue.js?',
                'dap_an_1' => 'Quản lý giao diện',
                'dap_an_2' => 'Quản lý dữ liệu',
                'dap_an_3' => 'Quản lý route',
                'dap_an_4' => 'Quản lý event',
                'dap_an_dung' => 2,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Sự kiện nào được kích hoạt khi dữ liệu thay đổi trong Vue.js?',
                'dap_an_1' => 'watch',
                'dap_an_2' => 'computed',
                'dap_an_3' => 'update',
                'dap_an_4' => 'change',
                'dap_an_dung' => 3,
                'tinh_trang' => 1,
            ],
            [
                'cau_hoi' => 'File cấu hình chính trong dự án Vue.js là gì?',
                'dap_an_1' => 'package.json',
                'dap_an_2' => 'vue.config.js',
                'dap_an_3' => 'webpack.config.js',
                'dap_an_4' => 'app.vue',
                'dap_an_dung' => 2,
                'tinh_trang' => 0,
            ],
            [
                'cau_hoi' => 'Cách nào để truyền dữ liệu giữa các component cha và con trong Vue.js?',
                'dap_an_1' => 'Sử dụng props',
                'dap_an_2' => 'Sử dụng events',
                'dap_an_3' => 'Sử dụng methods',
                'dap_an_4' => 'Sử dụng Vuex',
                'dap_an_dung' => 1,
                'tinh_trang' => 1,
            ],
        ]);
    }
}
